# Generated by Django 3.2 on 2022-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
